kind: Deployment
apiVersion: apps/v1
metadata:
  name: phone-calculator
spec:
  replicas: 0
  selector:
    matchLabels:
      app: phone-calculator
  template:
    metadata:
      labels:
        app: phone-calculator
    spec:
      containers:
        - name: phone-calculator
          image: noamyiz15/phone-calculator
          env:
          - name: APP_PORT
            value: "3000"
          - name: NGINX_ENVSUBST_OUTPUT_DIR
            value: "/etc/nginx"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
#            runAsNonRoot: true
          resources:
            limits:
                cpu: '1'
                memory: 250Mi
      restartPolicy: Always
  

---

kind: Service
apiVersion: v1
metadata:
  name: phone-calculator
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30000
  selector:
    app: phone-calculator